### ISSUE TITLE
[GET] Need the ability to retrieve an item

### ISSUE THREAD

**Issue by Tserfaty** [CSCI-GA-2820-SP23-001/shopcarts#10]
**As a** shopper
**I need** the ability to retrieve an item from my shopcart
**So that** I can see that specific item
   
 ### Details and Assumptions
 * Request type: GET
 * Return 'HTTP_200_OK' if the resource successfully retrieved
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a user is viewing their shopping cart
 When they retrieve an item
 Then the item will be displayed
```

**Comment by kneelanda** [comment]
Is this still relevant? If not maybe we can close it?
