### ISSUE TITLE
[DELETE] Need the ability to delete shopcart

### ISSUE THREAD

**Issue by smf9560** [CSCI-GA-2820-SP23-001/shopcarts#11]
**As a** shopper
**I need** the ability to delete a shopcart
**So that** remove all items from the cart.
   
 ### Details and Assumptions
 * Request type: DELETE
 * Return '204_NO_CONTENT' if the resource successfully deleted the  shopcart 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a user is viewing their shopping cart
 When they delete the shopcart
 Then the shopping cart will emptied.
```

**Comment by Git-ittt** [comment]
I'm under the assumption the acceptance criteria is all measurable/actionable, so perhaps in this case something more along the lines of:
Given the user is viewing the shopping cart
When they change the amount of a product in it
Then the shopping cart reflects the new amount
