### ISSUE TITLE
Need the ability to link back to product pages from items in shopcart

### ISSUE THREAD

**Issue by kneelanda** [CSCI-GA-2820-SP23-001/shopcarts#14]
**As a** shopper
**I need** an ability to get back to the product page
**So that** I can read more about the details before I make my purchase

Details and Assumptions
- Assuming that there is an existing page to link back to

Acceptance Criteria
Given that the shopper is viewing an item in the cart
When the shopper clicks on the item
Then the shopper is redirected to the product page

**Comment by smf9560** [comment]
I believe the format needs to be like this:

**As a** [role]
**I need** [function]  
**So that** [benefit]  
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [action taken]
 Then [outcome observed]
```
