### ISSUE TITLE
ACTION a BDD .feature file to test RESTful API

### ISSUE THREAD

**Issue by Git-ittt** [CSCI-GA-2820-SP23-001/shopcarts#53]
**As a** tester
**I need** to create a BDD .feature file to test a RESTful API
**So that** I can ensure that the API is functioning correctly and meets all requirements
   
 ### Details and Assumptions
 * The RESTful API has been developed and is ready to be tested using BDD
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a RESTful API that needs to be tested
 When I create a BDD .feature file that includes scenarios with given-when-then steps
 Then I can verify that the API behaves as expected under various conditions, such as different input data, invalid inputs, and edge cases, resulting in a comprehensive and reliable test suite
```

**Comment by ctn8176** [comment]
fulfilled - another ticket was created
